### PR TITLE
Change alias, to avoid clash with yajra Datatables pkg

### PR DESCRIPTION
**Pull request by drbyte**
Changed alias from `datatables` to `bllimdatatables`, so it doesn't clash with yajra datatables pkg.

### CODE REVIEW

**Comment by svenluijten** [comment]
This would also need an update to [the `ServiceProvider`](https://github.com/antonioribeiro/laravel4-datatables-package/blob/master/src/Bllim/Datatables/DatatablesServiceProvider.php#L31), right? Otherwise it won't be able to resolve `bllimdatatables` from the container.

**Comment by drbyte** [comment]
Argh - Github didn't merge my 2 commits properly.

Thanks @svenluijten !

**Comment by svenluijten** [comment]
The `->provides()` method in that same service provider would need an update.

Although, the provider isn't even deferred (`$defer` is `false`), so that method isn't even checked.

**Comment by drbyte** [comment]
> The `->provides()` method in that same service provider would need an update.
> 
> Although, the provider isn't even deferred (`$defer` is `false`), so that method isn't even checked.

Ya, I looked at that, but wasn't certain ... and it all "worked", so I left it. 
Thanks for connecting the dots to the Deferred property ... that makes sense.

**Comment by antonioribeiro** [comment]
Renamed it again, removed deferred stuff, which, by the way, is a whole different thing in Laravel 6, and tagged v1.4.12.

**Comment by drbyte** [comment]
Great! Thanks 👍

**Pull request merged**
